docs: add model serving feature
lablup/backend.ai-docs-webui pull request #43
Opened 2023-09-14 09:10 UTC by lizable

This PR adds the new feature of ``23.09``, "model serving".

2023-09-26 07:34 UTC, agatha197 requested changes
<img width="538" alt="image" src="https://github.com/lablup/backend.ai-docs-webui/assets/28584164/c00d0133-d130-454c-b032-e66febd1cc34">
When I tested model serving a few days ago, if the `pre_start_actions` option is an empty string, it occurs error. Please fill it with `[]` (maybe?) or remove it.

2023-09-26 07:34 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +"Backend.AI(백엔드닷에이아이)에서는 모델 학습 단계의 개발 환경 구축 및 자원 관리를 쉽게 해주는 것 뿐 만 아니라,모델을 "
```suggestion
"Backend.AI(백엔드닷에이아이)에서는 모델 학습 단계의 개발 환경 구축 및 자원 관리를 쉽게 해주는 것뿐만 아니라, 모델을 "
```

2023-09-26 07:34 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +"정보를 담고 있는 파일입니다. 이 파일은 추론 서비스 엔진을 담고 있는 컨테이너 이미지와는 독립적으로 모델 타입 폴더에 저장합니다."
```suggestion
"정보를 담고 있는 파일입니다. 이 파일을 추론 서비스 엔진을 담고 있는 컨테이너 이미지와는 독립적으로 모델 타입 폴더에 저장합니다."
```

2023-09-26 07:34 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +"무방합니다.``/``(슬래시) 가 추가된 항목은 슬래시 앞 키의 하위 키에 대한 설명입니다."
<img width="64" alt="image" src="https://github.com/lablup/backend.ai-docs-webui/assets/28584164/22aa990c-8a97-4538-9ad5-71fc75275323">

```suggestion
"무방합니다.``/`` (슬래시) 가 추가된 항목은 슬래시 앞 키의 하위 키에 대한 설명입니다."
```

2023-09-26 07:34 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +msgstr "``start_command``항목 내"
```suggestion
msgstr "``start_command`` 항목 내"
```

2023-09-26 07:51 UTC, agatha197 requested changes

2023-09-26 07:51 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +"기준으로 서비스하려는 세션을 몇 개까지 만들어야 할 지 설정하는데, 이 값을 기준으로 하게 됩니다."
```suggestion
"기준으로 서비스하려는 세션을 몇 개까지 만들어야 할지 설정하는데, 이 값을 기준으로 하게 됩니다."
```

2023-09-26 07:51 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +"사용하지 않는 경우라면, 모델 서비스를 종료하는 것이 좋습니다. 모델 서비스를 종료하려면, 제어 탭에서 휴지통아이콘을 클릭합니다. "
```suggestion
"사용하지 않는 경우라면, 모델 서비스를 종료하는 것이 좋습니다. 모델 서비스를 종료하려면, 제어 탭에서 휴지통 아이콘을 클릭합니다. "
```

2023-09-26 07:51 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +msgstr "너무 적은 양의 자원을 모델 서비스 생성시 라우팅에 할당한 경우"
```suggestion
msgstr "모델 서비스 생성 시 너무 적은 양의 자원을 라우팅에 할당한 경우"
```

2023-09-26 07:51 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +"엔드포인트 명을 클릭해 모델 서비스의 상세 정보를 확인할 수 있습니다. 이후 모델 서비스의 라우팅 정보에서 서비스 엔트포인트를 "
```suggestion
"엔드포인트 명을 클릭해 모델 서비스의 상세 정보를 확인할 수 있습니다. 이후 모델 서비스의 라우팅 정보에서 서비스 엔드포인트를 "
```

2023-09-26 07:51 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +"확인할 수 있는데, 이 엔드포인트는 서비스 생성시 외부 에 공개할 수 있는 \"Open to Public\" 값이 활성화 된 경우,"
```suggestion
"확인할 수 있는데, 이 엔드포인트는 서비스 생성시 외부에 공개할 수 있는 \"Open to Public\" 값이 활성화 된 경우,"
```

2023-10-05 03:42 UTC, yomybaby requested changes

2023-10-05 03:42 UTC, yomybaby commented on docs/model_serving/model_serving.rst
> +.. image:: edit-model-service-dialog.png
This image is not related to `Generating Token`.

2023-10-05 03:42 UTC, yomybaby commented on docs/model_serving/model_serving.rst
> +.. image:: edit-model-service-dialog.png
<img width="806" alt="image" src="https://github.com/lablup/backend.ai-docs-webui/assets/621215/0aac0763-a34b-4d94-b6c9-8c4ad7e6427a">

2023-10-05 06:49 UTC, yomybaby commented
@lizable 
On `Solution` parts, is it `Clear error and retry` not `Refresh`?
<img width="638" alt="image" src="https://github.com/lablup/backend.ai-docs-webui/assets/621215/e46bacbb-b161-4525-b35c-b747c7e372ad">

2023-10-05 11:06 UTC, merged