Update resource policy page guide
lablup/backend.ai-docs-webui pull request #62
Opened 2024-06-04 08:06 UTC by agatha197

related PR: https://github.com/lablup/backend.ai-webui/pull/2357

Introduce a new resource policy page guide to admin menu.

2024-06-04 10:07 UTC, lizable approved these changes
LGTM.

2024-06-11 03:39 UTC, YEONFEEL96 requested changes
EN/KR Reviewed. 
This chunk is so big, so need more time to analyze.
This review only includes major issue. Minor issues will be fixed next time.

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +resource policy page, you can set restrictions on various settings related to folders such as
```suggestion
resource policy page, users can set restrictions on various settings related to folders such as
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +  If the user's folder count exceeds this value, the user cannot create a new folder.
```suggestion
  If the user's folder count exceeds this value, user cannot create a new folder.
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +- Max Folder Size: The maximum size of the user's storage space. If the
```suggestion
- Max Folder Size: The maximum size of the user's storage space. If 
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +  user's storage space exceeds this value, the user cannot create a new data
```suggestion
  user's storage space exceeds this value, user cannot create a new data
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +  scheduler and potentially lead to system downtime, so please exercise caution when
```suggestion
  scheduler and potentially lead to system downtime, so please caution when
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +- Max Customized Image Count: The maximum number of customized images that the
```suggestion
- Max Customized Image Count: The maximum number of customized images that 
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +  user can create. If the user's customized image count exceeds this value, the
```suggestion
  user can create. If user's customized image count exceeds this value, 
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +To update, click the gear icon button in the control column. To delete, click the trash can
```suggestion
To update, click the 'Setting (Gear)' button in the control column. To delete, click the trash can
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +icon button.
```suggestion
button.
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +   Changing a resource policy can affect all users that use that user resource policy, so use
```suggestion
   Changing a resource policy may affect all users who use that policy, so use
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +   it with care.
```suggestion
   it with caution.
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +Similar to keypair resource policy, you can select and display only the columns you want by
```suggestion
Similar to keypair resource policy, users can select and display only columns users want by
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +clicking the gear icon button at the bottom right of the table.
```suggestion
clicking the 'Setting (Gear)' button at the bottom right of the table.
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +To create a new project resource policy, click the Create button at the top right of the table.
```suggestion
To create a new project resource policy, click the 'Create' button at the top right of the table.
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +If you want to make changes, click the gear icon button in the control column. Resource policy
```suggestion
If you want to make changes, click the 'Setting (Gear)' button in the control column. Resource policy
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +   Changing a resource policy can affect all projects that use that project resource policy,
```suggestion
   Changing a resource policy may affect all users who use that policy,
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +   so use it with care.
```suggestion
   so use it with caution.
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/admin_menu/admin_menu.rst
> +You can select and display only the columns you want by clicking the gear icon button at the
```suggestion
You can select and display only the columns you want by clicking the 'Setting (Gear)' button at the
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"뜨고, 다시 이 메뉴를 클릭하면 각 탭 자원 별 CSV export 다이얼로그가 뜹니다. 필요한 경우 적당한 파일 이름을 쓰고 "
```suggestion
"나타나고, 다시 해당 메뉴를 클릭하면 각 탭 자원 별 CSV export 다이얼로그가 나타납니다. 필요한 경우 적당한 파일 이름을 기입하고, "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  "Project  선택합니다. 이 때, 목표 프로젝트 사용자 B 가 속한 프로젝트로 설정합니다. Permission 은 Read-"
```suggestion
"Project를 선택합니다. 이 때, 목표 프로젝트는 사용자 B 가 속한 프로젝트로 설정합니다. Permission 은 Read-"
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  "Only 로 설정하였습니다."
```suggestion
"Only 로 설정했습니다."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  "별도의 초대 절차 없이 조회되는 것을 확인합니다. Permission 열에는 역시 R(읽기전용)이 표시된 것을 확인할 수 있습니다."
```suggestion
"별도의 초대 절차 없이 조회되는 것을 확인합니다. Permission 열에 R(읽기전용) 표시가 나타난 것을 확인할 수 있습니다."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"자원 정책을 수정하려면 기본 정책 그룹의 제어 열에 있는 기어 아이콘을 클릭합니다. 자원 정책 업데이트 다이얼로그에서 정책 이름을 "
```suggestion
"자원 정책을 수정하려면 기본 정책 그룹의 제어 열에 있는 '설정' 아이콘을 클릭합니다. 자원 정책 업데이트 다이얼로그에서 정책 이름을 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"제외한 모든 옵션이 편집 가능하며, 이는 목록에서 자원 정책을 구별하는 주요 키 역할을 합니다. 여기에선 CPU, RAM 및 "
```suggestion
"제외한 모든 옵션을 편집할 수 있으며, 이는 목록에서 자원 정책을 구별하는 주요 키 역할을 합니다. 여기에서는 CPU, RAM 및 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  msgstr "자원 정책 창의 각 옵션에 대한 자세한 내용은 아래 설명을 참조하시기 바랍니다."
```suggestion
msgstr "자원 정책 창의 각 옵션에 대한 자세한 내용은 아래 설명을 참조하세요."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  msgstr "CPU : CPU 코어 최대 할당 가능량을 설정합니다. (최대 입력 값: 512)"
```suggestion
msgstr "CPU : CPU 코어 최대 할당 가능량 설정. (최대 입력 값: 512)"
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"Memory : GB 단위로 최대 할당 가능한 메모리 양을 설정합니다. 최대 할당 가능한 GPU 메모리 양의 두 배 이상으로 "
```suggestion
"Memory : GB 단위로 최대 할당 가능한 메모리 양 설정. 최대 할당 가능한 GPU 메모리 양의 두 배 이상으로 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"설정하는 것을 권장합니다. (최대 입력 값: 1024)"
```suggestion
"설정하는 것이 권장됨. (최대 입력 값: 1024)"
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"CUDA-capable GPU : 할당 가능한 최대 물리 GPU 개수를 설정합니다. 서버에서 GPU 분할 가상화 기능이 켜져 있는 "
```suggestion
"CUDA-capable GPU : 할당 가능한 최대 물리 GPU 개수를 설정합니다. 서버에서 GPU 분할 가상화 기능이 켜져 있는 "
```
```suggestion
"CUDA-capable GPU : 할당 가능한 최대 물리 GPU 개수 설정. 서버에서 GPU 분할 가상화 기능이 켜져 있는 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +" 있으면, 물리 GPU 를 분할하여 여러 사용자 세션에 나눠어 배치하고 효율적으로 사용할 수 있습니다. 할당 가능한 최대 분할 "
```suggestion
" 있으면, 물리 GPU 를 분할하여 여러 사용자 세션에 나눠어 배치하고 효율적으로 사용할 수 있음. 할당 가능한 최대 분할 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"GPU 양은 여기서 설정합니다. 만약 서버에 GPU 분할 가상화 기능이 꺼져 있다면 이 항목은 효과가 없습니다. (최대 입력 값: "
```suggestion
"GPU 양을 여기서 설정하며, 서버에 GPU 분할 가상화 기능이 꺼져 있다면 이 항목은 적용되지 않음. (최대 입력 값: "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"Session Lifetime (sec.): 세션이 예약 시간 이후 활성 상태로 존재할 수 있는 최대 시간을 제한합니다. 이 때, "
```suggestion
"Session Lifetime (sec.): 세션이 예약 시간 이후 활성 상태로 존재할 수 있는 최대 시간. "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"활성 상태는 ``PENDING`` 및 ``RUNNING`` 상태를 포함합니다. 예약 후 설정된 시간이 지나면 세션은 지속적으로 "
```suggestion
"활성 상태는 ``PENDING`` 및 ``RUNNING`` 상태를 포함함. 예약 후 설정된 시간이 지나면 세션이 사용중이라 할지라도 강제로 종료됨. "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"사용중이라 할지라도 강제로 종료됩니다. 연산 세션이 무한히 실행되는 것을 방지하고자 할 때 유용하게 사용할 수 있습니다."
```suggestion
"사용중이라 할지라도 강제로 종료됩니다. 연산 세션이 무한히 실행되는 것을 방지하고자 할 때 유용하게 사용할 수 있습니다."
```
```suggestion
"사용중이라 할지라도 강제로 종료됩니다. 연산 세션이 무한히 실행되는 것을 방지하고자 할 때 유용하게 사용할 수 있습니다."
```
```suggestion
"연산 세션이 무한히 실행되는 것을 방지하고자 할 때 유용한 옵션."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  "지정되어 있을 경우, 이 정책에 영향을 받는 사용자는 동시에 3 개를 넘는 연산 세션을 생성할 수 없습니다. (최대 입력 값: "
(편집불가 열) 키 페어를 통해 동시에 생성할 수 있는 최대 연산 새션의 개수. 예를 들어, 값이 3으로

```suggestion
"지정되어 있을 경우, 해당 정책에 영향을 받는 사용자는 동시에 3개가 넘는 연산 세션을 생성할 수 없음. (최대 입력 값: "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"설정할 수 있습니다. (최대 입력 값: 15552000(초) (약 180 일))"
```suggestion
"설정할 수 있음. (최대 입력 값: 15552000(초) (약 180 일))"
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  "인식되어 있는 상태일지라도, Allowed hosts 정책으로 허용되지 않은 경우 사용자는 해당 NFS 에 접근할 수 없습니다."
```suggestion
"인식되어 있는 상태일지라도, Allowed hosts 정책으로 허용되지 않은 경우 사용자는 해당 NFS 에 접근할 수 없음."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"(23.09.4 이후로 사용 중단) Max. #: 생성 또는 공유 초대 받을 수 있는 저장 폴더의 최대 개수입니다. (최대 입력 "
```suggestion
"(23.09.4 이후로 사용 중단) Max. #: 생성 또는 공유, 초대 받을 수 있는 저장 폴더의 최대 개수. (최대 입력 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  "Controls 열에 위치한 톱니바퀴 설정 버튼을 누른 후 Select Policy 필드를 클릭하여 선택하면 됩니다."
```suggestion
"Controls 열에 위치한 '설정' 버튼을 누른 후, Select Policy 필드를 클릭하여 선택합니다."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"will appears. click Delete button to delete."
```suggestion
"will appears. click 'Delete' button to erase."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"Control 열의 휴지통 아이콘을 클릭하여 각 리소스 키페어를 삭제할 수 있습니다. 아이콘을 클릭하면 확인 팝업이 나타납니다. "
```suggestion
"Control 열의 '휴지통' 아이콘을 클릭하여 각 리소스 키페어를 삭제할 수 있습니다. 아이콘을 클릭하면 확인 팝업이 나타납니다. "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"삭제하려면 Delete 버튼을 클릭하세요."
```suggestion
"삭제하려면 'Delete' 버튼을 클릭하세요."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  "위해서는 반드시 해당 자원 정책을 선택한 사용자가 남아 있지 않도록 하십시오."
```suggestion
"위해서는 반드시 해당 자원 정책을 선택한 사용자가 남아 있지 않아야 합니다."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"특정 열을 숨기거나 보고 싶다면 테이블 우측 하단의 기어 아이콘을 클릭합니다. 그러면 아래 다이얼로그가 표시되어 보고 싶은 열을 "
```suggestion
"특정 열을 숨기거나 보고 싶다면 테이블 우측 하단의 '설정' 아이콘을 클릭합니다. 이후에는 아래에 다이얼로그가 표시되어 보고 싶은 열을 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +msgstr "Name: 사용자 자원 정책의 이름입니다."
```suggestion
msgstr "Name: 사용자 자원 정책의 이름."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"Max Folder Count: 사용자가 생성할 수 있는 최대 폴더 수입니다. 사용자의 폴더 수가 이 값을 초과하면 새 폴더를 "
```suggestion
"Max Folder Count: 사용자가 생성할 수 있는 최대 폴더 수. 사용자의 폴더 수가 해당 값을 초과하면 새 폴더를 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"생성할 수 없습니다. 무제한으로 설정된 경우에는 “∞“로 표시됩니다."
```suggestion
"생성할 수 없게 되며, 무제한으로 설정된 경우에는 “∞“로 표시됨."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"Max Folder Size: 사용자의 저장 공간의 최대 크기입니다. 사용자의 저장 공간이 이 값을 초과하면 사용자는 새 데이터 "
```suggestion
"Max Folder Size: 사용자의 저장 공간의 최대 크기. 사용자의 저장 공간이 해당 값을 초과하면 사용자는 새 데이터 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"폴더를 만들 수 없습니다. 무제한으로 설정된 경우에는 “∞“로 표시됩니다."
```suggestion
"폴더를 만들 수 없게 되며, 무제한으로 설정된 경우에는 “∞“로 표시됨."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"수입니다. 이 값을 증가시키면 세션 스케줄러에 부하가 가해질 수 있고, 잠재적으로 시스템 다운타임으로 이어질 수 있으니 이 설정을 "
```suggestion
"수. 해당 값을 증가시키면 세션 스케줄러에 부하가 가해질 수 있고, 잠재적인 시스템 다운타임으로 이어질 수 있습니다. 따라서, 이 설정을 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"조정할 때 주의하시기 바랍니다."
```suggestion
"조정할 때는 주의가 필요합니다."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"Max Customized Image Count: 사용자가 생성할 수 있는 최대 사용자 정의 이미지 수입니다. 사용자의 사용자 정의"
```suggestion
"Max Customized Image Count: 사용자가 생성할 수 있는 최대 사용자 정의 이미지 개수. 사용자의 사용자 정의"
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +" 이미지 수가 이 값을 초과하면 사용자는 새로운 사용자 정의 이미지를 만들 수 없습니다. 사용자 정의 이미지에 대해 더 알고 "
```suggestion
" 이미지 수가 이 값을 초과하면, 사용자는 새로운 사용자 정의 이미지를 만들 수 없음. 사용자 정의 이미지에 대해 더 알고 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"싶다면, :ref:`나의 실행 환경<my-environments>` 섹션을 참조해주세요."
```suggestion
"싶다면, :ref:`나의 실행 환경<my-environments>` 섹션을 참조 할 수 있음."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +msgstr "ID: 사용자 자원 정책의 ID입니다."
```suggestion
msgstr "ID: 사용자 자원 정책의 ID."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +msgstr "Created At: 사용자 자원 정책이 생성된 날짜와 시간입니다."
```suggestion
msgstr "Created At: 사용자 자원 정책이 생성된 날짜와 시간."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +msgstr "자원 정책을 변경하면 해당 사용자 자원 정책을 사용하는 모든 사용자에게 영향을 줄 수 있으므로 주의해서 사용하시길 바랍니다."
```suggestion
msgstr "자원 정책을 변경하면 해당 사용자 자원 정책을 사용하는 모든 사용자에게 영향을 줄 수 있습니다. 자원 정책을 변경할 때는 사용자의 주의가 필요합니다."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +msgstr "키페어 자원 정책과 마찬가지로, 원하는 열만 선택하여 표시하려면 테이블 오른쪽 하단의 기어 아이콘 버튼을 클릭하세요."
```suggestion
msgstr "키페어 자원 정책과 마찬가지로, 원하는 열만 선택하여 표시하려면 테이블 오른쪽 하단의 '설정' 버튼을 클릭하세요."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +msgstr "Resource Policy 페이지의 Project 탭을 클릭하면 프로젝트 자원 정책 목록을 볼 수 있습니다."
```suggestion
msgstr "Resource Policy 페이지의 'Project' 탭을 클릭하면 프로젝트 자원 정책 목록을 볼 수 있습니다."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +msgstr "테이블 오른쪽 위에 있는 Create 버튼을 클릭하여 새로운 프로젝트 자원 정책을 생성할 수 있습니다."
```suggestion
msgstr "테이블 오른쪽 위에 있는 'Create' 버튼을 클릭하여 새로운 프로젝트 자원 정책을 생성할 수 있습니다."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"Max Folder Count: 관리자가 생성할 수 있는 프로젝트 폴더의 최대 수입니다. 프로젝트 폴더 수가 이 값을 초과하면 "
```suggestion
"Max Folder Count: 관리자가 생성할 수 있는 프로젝트 폴더의 최대 개수. 프로젝트 폴더 수가 해당 값을 초과하면 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"관리자는 새 프로젝트 폴더를 생성할 수 없습니다. 무제한으로 설정된 경우에는 “∞“로 표시됩니다."
```suggestion
"관리자가 새 프로젝트 폴더를 생성할 수 없게 되며, 무제한으로 설정된 경우에는 “∞“로 표시됨."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"Max Folder Size: 프로젝트의 저장 공간의 최대 크기입니다. 프로젝트의 저장 공간이 이 값을 초과하면 관리자는 새 "
```suggestion
"Max Folder Size: 프로젝트의 저장 공간의 최대 크기. 프로젝트의 저장 공간이 이 값을 초과하면 관리자가 새 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"프로젝트 폴더를 만들 수 없습니다. 무제한으로 설정된 경우에는 “∞“로 표시됩니다."
```suggestion
"프로젝트 폴더를 생성할 수 없게 되며, 무제한으로 설정된 경우에는 “∞“로 표시됨."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"변경을 원하면 제어 열의 기어 아이콘 버튼을 클릭하세요. 자원 정책 이름은 편집할 수 없습니다. 삭제는 휴지통 아이콘 버튼을 "
```suggestion
"변경을 원하면 제어 열의 '설정' 아이콘 버튼을 클릭하세요. 자원 정책 이름은 편집할 수 없습니다. 삭제는 '휴지통' 버튼을 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +msgstr "자원 정책을 변경하면 해당 프로젝트 자원 정책을 사용하는 모든 프로젝트에 영향을 줄 수 있으므로 주의해서 사용하시길 바랍니다."
```suggestion
msgstr "자원 정책을 변경하면 해당 사용자 자원 정책을 사용하는 모든 사용자에게 영향을 줄 수 있습니다. 자원 정책을 변경할 때는 사용자의 주의가 필요합니다."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +msgstr "원하는 열만 선택하여 표시하려면 테이블 오른쪽 하단의 기어 아이콘 버튼을 클릭하세요."
```suggestion
msgstr "원하는 열만 선택하여 표시하려면 테이블 오른쪽 하단의 '설정' 버튼을 클릭하세요."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  "경우, 해당 요청은 자동으로 이미지 최소 자원 요구량으로 조정된 후 생성이 진행됩니다."
```suggestion
"경우, 해당 요청은 자동으로 이미지 최소 자원 요구량으로 조정된 후 생성됩니다."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  msgstr "오프라인 환경일 경우 기본 도커 레지스트리에 접근이 불가능하므로, 우측 휴지통 아이콘을 클릭하여 삭제하면 됩니다."
```suggestion
msgstr "오프라인 환경일 경우 기본 도커 레지스트리에 접근이 불가능하므로, 우측 '휴지통' 버튼을 클릭하여 삭제하면 됩니다."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  "Environments의 Registries 탭을 클릭하여 현재 연결되어 있는 도커 레지스트리의 정보를 확인할 수 있습니다. "
```suggestion
"Environments의 'Registries' 탭을 클릭하여 현재 연결되어 있는 도커 레지스트리의 정보를 확인할 수 있습니다. "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  msgstr "Registry Hostname을 제외하고 이미 존재하는 레지스트리 정보를 수정할 수도 있습니다."
```suggestion
msgstr "Registry Hostname을 제외하고 이미 존재하는 레지스트리 정보를 수정할 수 있습니다."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  msgstr "리소스 그룹에서 스케줄러 관련 옵션(Scheduler Options)을 추가 설정할 수도 있습니다. 각 항목은 다음 의미를 가집니다."
```suggestion
msgstr "리소스 그룹에서 스케줄러 관련 옵션(Scheduler Options)을 추가 설정할 수도 있습니다. 각 항목별 설정은 아래 내용을 참고하세요."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"수 있습니다. 하나 이상의 세션 타입을 허용해야 합니다. 허용되는 세션 타입은 Interactive, Batch, Inference"
```suggestion
"수 있음. 하나 이상의 세션 타입을 허용해야 하며, 허용되는 타입은 Interactive, Batch, Inference 임."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  "취소합니다. 무한히 PENDING 상태에 머무르는 세션을 방지하고자 할 때 기준 시간을 설정합니다. 0을 설정하면 Pending "
```suggestion
"취소함. 무한히 PENDING 상태에 머무르는 세션을 방지하고자 할 때 기준 시간을 설정할 수 있음. 0을 설정하면 Pending "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  "timeout을 적용하지 않습니다."
```suggestion
"timeout이 적용되지 않음."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"재시도 횟수입니다. 한 PENDING 세션이 그 뒤에 요 청된 세션의 스케줄링을 무한히 막는 경우(Head-of-line "
```suggestion
"재시도 횟수. 한 PENDING 세션이 그 뒤에 요청된 세션의 스케줄링을 무한히 막는 경우 (Head-of-line "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"blocking, HOL)를 방지하 기 위해 설정할 수 있습니다. 따로 설정하지 않는 경우에는 Etcd 에 설정된 글로벌 값 "
```suggestion
"blocking, HOL)를 방지하기 위해 설정할 수 있음. 따로 설정하지 않는 경우에는 Etcd 에 설정된 글로벌 값 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
> +"(num_retries_to_skip, 기본 3 회)을 사용하게 됩니다."
```suggestion
"(num_retries_to_skip, 기본 3 회)을 사용함."
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  "쿼타를 설정하기 위해서는, 자원 페이지의 저장소(스토리지) 탭에 먼저 접근해야 합니다. 그리고, 컨트롤 컬럼의 톱니바퀴 아이콘을 "
```suggestion
"쿼타를 설정하기 위해서는 자원 페이지의 '저장소(Storage)' 탭을 누르고, 컨트롤 컬럼의 '설정' 버튼을 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  "가능합니다. 저장소의 쿼타 설정 기능 제공 여부에 관계없이, 쿼타 설정 페이지는 제공하나, 내부적으로 쿼타 설정을 지원하지 않는 "
```suggestion
"가능합니다. 저장소의 쿼타 설정 기능 제공 여부에 관계없이 쿼타 설정 페이지를 제공하지만, 내부적으로 쿼타 설정을 지원하지 않는 "
```

2024-06-11 03:39 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/admin_menu/admin_menu.po
>  "저장소에 대해서는 쿼타 설정할 수 없습니다."
```suggestion
"저장소에 대해서는 쿼타를 설정할 수 없습니다."
```

2024-06-13 03:27 UTC, YEONFEEL96 approved these changes
Looks good to me.

2024-06-13 03:58 UTC, merged