docs: update model-serving with mount vfolder and validation
lablup/backend.ai-docs-webui pull request #65
Opened 2024-06-04 11:56 UTC by lizable

related PR: [lablup/backend.ai-webui#2437](https://github.com/lablup/backend.ai-webui/pull/2437)

This PR updates model serving menu with updated UI and features:
- additional mounts on service creation/modification
- arbitrary setting on model storage mount path and model definition file path
- model validation

Preview of model serving pages
[Backend.AI WebUI Docs 24.03.4-model_serving.pdf](https://github.com/user-attachments/files/15550879/Backend.AI.WebUI.Docs.24.03.4-model_serving.pdf)
[Backend.AI WebUI Docs 24.03.4-model_serving-ko.pdf](https://github.com/user-attachments/files/15550882/Backend.AI.WebUI.Docs.24.03.4-model_serving-ko.pdf)

2024-06-05 02:54 UTC, agatha197 requested changes
I left minor suggestions :)

2024-06-05 02:54 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +msgstr "모델 서비스 생성하기"
```suggestion
msgstr "모델 서비스 생성하기/유효성 검사하기"
```
Or
```suggestion
msgstr "모델 서비스 생성하기/검사하기"
```

2024-06-05 02:54 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +msgstr "그리고, 이미지 환경과 리소스 그룹을 선택합니다. 리소스 그룹은 모델 서비스에 할당될 수 있는 리소스의 집합입니다."
```suggestion
msgstr "그리고, 이미지 환경과 자원 그룹을 선택합니다. 자원 그룹은 모델 서비스에 할당될 수 있는 자원의 집합입니다."
```
Let's standardize the terminology for resource group to "자원 그룹".

2024-06-05 02:54 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +#~ msgstr "우선 서비스 이름과 모델 서비스에 사용할 모델 타입의 가상 폴더를 선택합니다. "
```suggestion
```

2024-06-05 02:54 UTC, agatha197 commented on docs/model_serving/model_serving.rst
> +   model definition file inside the directory
```suggestion
   model definition file inside the directory.
```

2024-06-05 02:54 UTC, agatha197 commented on docs/model_serving/model_serving.rst
> +   uploaded in model storage path. default value is ``model-definition.yaml``.
```suggestion
   uploaded in the model storage path. The default value is ``model-definition.yaml``.
```

2024-06-05 02:54 UTC, agatha197 commented on docs/model_serving/model_serving.rst
> +by container log. when result is set to ``Finished``, then validation check is finished.
```suggestion
whether execution is available or not(due to any errors during execution.) By clicking the ``Validate`` button at the bottom-left of the service launcher, a new popup for listening to validation events will pop up. In the popup modal, you can check the status through the container log. When the result is set to ``Finished``, then the validation check is finished.
```

2024-06-05 03:01 UTC, agatha197 requested changes
![image](https://github.com/lablup/backend.ai-docs-webui/assets/28584164/46558e51-6e26-45be-90f2-be7ceb8808af)
Some sentences end with a period(.), while others do not. Additionally, some end with a noun, while others end with a verb. Could you please make the style consistent throughout the document?

2024-06-05 08:06 UTC, lizable commented
> ![image](https://private-user-images.githubusercontent.com/28584164/336669529-46558e51-6e26-45be-90f2-be7ceb8808af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzUwNTIsIm5iZiI6MTcxNzU3NDc1MiwicGF0aCI6Ii8yODU4NDE2NC8zMzY2Njk1MjktNDY1NThlNTEtNmUyNi00NWJlLTkwZjItYmU3Y2ViODgwOGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA4MDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYzc5MmVjMzBiMzI1NzAwZWQ1MWRmNjViN2M3ZGQ3MmMzN2ZiZmI3OTJhMTc1ZmM4MjJkOWRmMzVkNjFhMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RiNh_eHMiH7g2WY6V6ZMchCtJ_VIwKE3Fyy3H0Hx61E) Some sentences end with a period(.), while others do not. Additionally, some end with a noun, while others end with a verb. Could you please make the style consistent throughout the document?

Okay, good suggestion.

2024-06-05 08:52 UTC, agatha197 requested changes

2024-06-05 08:52 UTC, agatha197 commented on docs/model_serving/model_serving.rst
> +-  Single Node:When running a session, the managed node and worker nodes are
```suggestion
-  Single Node: When running a session, the managed node and worker nodes are 
```

2024-06-05 08:52 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
>  msgstr ""
translation is missing.

2024-06-05 08:52 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
>  msgstr "RAM: 연산 세션에 할당할 메모리의 용량(GiB)"
```suggestion
msgstr "RAM: 연산 세션에 할당할 메모리의 용량(GiB)."
```

2024-06-05 08:52 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
>  msgstr "GPU: 연산 세션에 할당할 GPU 단위"
```suggestion
msgstr "GPU: 연산 세션에 할당할 GPU 단위."
```

2024-06-05 08:52 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
>  msgstr "Shared Memory: 연산 세션에 할당할 공유 메모리의 용량(GiB). 연산 세션에 할당할 메모리의 용량보다는 작아야 함"
```suggestion
msgstr "Shared Memory: 연산 세션에 할당할 공유 메모리의 용량(GiB). 연산 세션에 할당할 메모리의 용량보다는 작아야 함."
```

2024-06-05 08:52 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +" 자원 그룹에 따라 AI 가속기를 선택하게 됨"
```suggestion
" 자원 그룹에 따라 AI 가속기를 선택하게 됨."
```

2024-06-05 08:52 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +msgstr "Single Node: 세션을 실행할 때에 관리 노드와 워커 노드들이 하나의 물리 노드 또는 가상 머신에 배치되는 경우"
```suggestion
msgstr "Single Node: 세션을 실행할 때에 관리 노드와 워커 노드들이 하나의 물리 노드 또는 가상 머신에 배치되는 경우."
```

2024-06-12 04:37 UTC, YEONFEEL96 requested changes
KR/EN Reviewed

2024-06-12 06:47 UTC, agatha197 requested changes

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/import_run/import_run.po
> +#~ msgstr "GitLab 저장소 불러오기"
```suggestion
```

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/login/login.po
> +#~ msgstr "가입 및 로그인"
```suggestion
```

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
>  msgstr "모델 정의 파일에 대한 키-값 설명"
```suggestion
msgstr "**모델 정의 파일에 대한 키-값 설명**"
```

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
>  msgstr "모델 서비스 생성에 실패한 경우"
```suggestion
msgstr "**모델 서비스 생성에 실패한 경우**"
```

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +"제어 탭에서 톱니바퀴 아이콘을 클릭하면 원하는 세션 수 값을 변경할 수 있는 모달이 뜨게 됩니다. 수정 모달은 모델 서비스를 "
```suggestion
"제어 탭에서 '설정' 버튼을 클릭하면 원하는 세션 수 값을 변경할 수 있는 모달이 뜨게 됩니다. 수정 모달은 모델 서비스를 "
```

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/model_serving/model_serving.po
> +"사용하지 않는 경우라면, 모델 서비스를 종료하는 것이 좋습니다. 모델 서비스를 종료하려면, 제어 탭에서 휴지통 아이콘을 클릭합니다."
```suggestion
"사용하지 않는 경우라면, 모델 서비스를 종료하는 것이 좋습니다. 모델 서비스를 종료하려면, 제어 탭에서 '휴지통' 버튼을 클릭합니다."
```

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/mount_vfolder/mount_vfolder.po
> +#~ msgstr "자동 마운트 폴더를 이용하여 연산 세션 환경 구성하기"
```suggestion
```

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/sessions_all/sessions_all.po
> +
```suggestion
```

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/sessions_all/sessions_all.po
>  "IMAGE`` 버튼을클릭합니다. 이렇게 만들어진 사용자 정의 이미지는 추후 세션 생성 시 사용할 수 있습니다. 단, 이미지 커밋을 "
```suggestion
"IMAGE' 버튼 을클릭합니다. 이렇게 만들어진 사용자 정의 이미지는 추후 세션 생성 시 사용할 수 있습니다. 단, 이미지 커밋을 "
```

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/sessions_all/sessions_all.po
>  "4글자에서 32자까지만 입력해야 합니다. 세션 이름을 입력한 뒤에는 ``PUSH SESSION TO CUSTOMIZED "
```suggestion
"4글자에서 32자까지만 입력해야 합니다. 세션 이름을 입력한 뒤에는 'PUSH SESSION TO CUSTOMIZED "
```

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/sftp_to_container/sftp_to_container.po
> +#~ msgstr "연산 세션에 SSH/SFTP 접속하기 (Linux/Mac/Visual Studio Code)"
```suggestion
```

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/vfolder/vfolder.po
> +"쿼타(가용량)는 쿼타 설정을 제공하는 저장소에서만 사용할 수 있습니다(XFS, CephFS, NetApp, Purestorage "
```suggestion
"쿼타(가용량)는 쿼타 설정을 제공하는 저장소에서만 사용할 수 있습니다. (XFS, CephFS, NetApp, Purestorage "
```

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/vfolder/vfolder.po
> +"등). 가용량 설정에 대해서는 :ref:`쿼타 설정 패널<quota-setting-panel>` 섹션을 참고하십시오."
```suggestion
"등) 가용량 설정에 대해서는 :ref:`쿼타 설정 패널<quota-setting-panel>` 섹션을 참고하십시오."
```

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/vfolder/vfolder.po
> +"Host: 폴더를 만들 NFS 호스트입니다. NFS 호스트가 여러 개인 경우 하나를 선택할 수 있습니다.선택한 호스트가 충분한 "
```suggestion
"Host: 폴더를 만들 NFS 호스트입니다. NFS 호스트가 여러 개인 경우 하나를 선택할 수 있습니다. 선택한 호스트가 충분한 "
```

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/vfolder/vfolder.po
>  " Folders 탭에 추가됩니다. Automount Folders는 연산 세션 생성 시 별도로 마운트 하지 않더라도 자동으로 홈 "
```suggestion
"리스트를 볼 수 있습니다. 폴더를 생성할 때 점(``.``)으로 시작하는 이름을 지정하면 'Folders' 탭이 아닌 'Automount"
" Folders' 탭에 추가됩니다. 자동 마운트 폴더는 연산 세션 생성 시 별도로 마운트 하지 않더라도 자동으로 홈 "
```

2024-06-12 06:47 UTC, agatha197 commented on docs/locale/ko/LC_MESSAGES/vfolder/vfolder.po
> +
```suggestion
```

2024-06-12 11:05 UTC, lizable commented on docs/locale/ko/LC_MESSAGES/import_run/import_run.po
> +#~ msgstr "GitLab 저장소 불러오기"
Let's apply these things as an separate issue(and PR) to split the "interests"(관심사 분리를 위해 별도 이슈로 다룹시다.)

2024-06-12 11:05 UTC, lizable commented on docs/locale/ko/LC_MESSAGES/login/login.po
> +#~ msgstr "가입 및 로그인"
Same here. PR gets too big.

2024-06-12 11:06 UTC, lizable commented on docs/locale/ko/LC_MESSAGES/vfolder/vfolder.po
> +"쿼타(가용량)는 쿼타 설정을 제공하는 저장소에서만 사용할 수 있습니다(XFS, CephFS, NetApp, Purestorage "
This as well.

2024-06-12 11:06 UTC, lizable commented on docs/locale/ko/LC_MESSAGES/vfolder/vfolder.po
> +"등). 가용량 설정에 대해서는 :ref:`쿼타 설정 패널<quota-setting-panel>` 섹션을 참고하십시오."
Here as well.

2024-06-13 03:57 UTC, agatha197 approved these changes
LGTM

2024-06-13 04:21 UTC, merged