docs: update sessions section
lablup/backend.ai-docs-webui pull request #86
Opened 2024-10-23 06:42 UTC by ironAiken2

2024-10-23 06:43 UTC, ironAiken2 commented
* **#86** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-docs-webui/86?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-25 06:34 UTC, YEONFEEL96 commented
- Modified english expression on /sessions-section/sessions_all.rst
- Matched menu name with actual WebUI interface
https://github.com/lablup/backend.ai-docs-webui/pull/86/commits/36c6e987e9416b71f1528ff9f6efaf494dc15c3b

2024-10-25 06:35 UTC, YEONFEEL96 submitted a review, later dismissed

2024-10-25 10:32 UTC, YEONFEEL96 requested changes
Question about version. Is it fine to leave this as 20.03?

2024-10-25 10:32 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/sessions_all/sessions_all.po
>  "Project-Id-Version: Backend.AI Console User Guide 20.03\n"
Still reviewing the document, but shouldn't this to be 24.09? @ironAiken2 
```suggestion
"Project-Id-Version: Backend.AI Console User Guide 24.09\n"
```

2024-11-11 08:54 UTC, YEONFEEL96 requested changes
Changed two small typos in english document.

2024-11-11 08:54 UTC, YEONFEEL96 commented on docs/sessions_all/sessions_all.rst
> +In ther first page, users can select the type of session, 'interactive' or 'batch'.
```suggestion
In the first page, users can select the type of session, 'interactive' or 'batch'. 
```

2024-11-11 08:54 UTC, YEONFEEL96 commented on docs/sessions_all/sessions_all.rst
> +Click the 'Edit' button located at the top right of each card to redirect to relevent page.
```suggestion
Click the 'Edit' button located at the top right of each card to redirect to relevant page.
```

2024-11-14 09:34 UTC, YEONFEEL96 approved these changes
LGTM!

2024-11-22 05:40 UTC, merged