docs: update vfolder images and descriptions
lablup/backend.ai-docs-webui pull request #89
Opened 2024-10-23 09:31 UTC by ironAiken2

2024-10-23 09:31 UTC, ironAiken2 commented
* **#89** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-docs-webui/89?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-12 06:50 UTC, YEONFEEL96 requested changes
I've made minor updates to the wording to align with the revisions in the current documentation.
However, there are certain aspects that cannot be modified via GithHub Suggestion at this point, which I will address in a subsequent PR.

2024-11-12 06:50 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/vfolder/vfolder.po
> +"선택된 모델을 폴더로 복제하려면 모달의 오른쪽 상단에 있는 '폴더로 복제'버튼을 클릭합니다. "
```suggestion
"모달의 오른쪽 상단에 있는 '폴더로 복제' 버튼을 클릭하면 선택된 모델을 폴더로 복제할 수 있습니다. "
```

2024-11-12 06:50 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/vfolder/vfolder.po
>  "사용해봅시다. 모델 카드 중 하나를 클릭하면, 모델에 대한 모든 정보를 나타내는 모달이 띄워지게 됩니다. 현재 모델 카드를 내 "
```suggestion
"사용해봅시다. 모델 카드 중 하나를 클릭하면, 모델에 대한 모든 정보를 나타내는 모달이 나타납니다. "
```

2024-11-12 06:50 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/vfolder/vfolder.po
>  "폴더로 가져오고 싶다면, 오른쪽 위의 'Clone to a folder' 버튼을 클릭해주세요."
```suggestion
"오른쪽 위의 'Clone to a folder' 버튼을 클릭하면 현대 모델 카드를 나의 폴더로 가져올 수 있습니다. "
```

2024-11-12 06:50 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/vfolder/vfolder.po
>  "있습니다. 바로 모델 서비스를 시작하려면 제어 열의 '모델 서빙' 버튼을 클릭합니다. 'model_folder' 라는 폴더에 대해 "
```suggestion
"있습니다. 제어 열의 '모델 서빙' 버튼을 클릭하여 바로 모델 서비스를 시작할 수 있습니다. 아래에서는 'model_folder' 라는 폴더에 대해 "
```

2024-11-12 06:50 UTC, YEONFEEL96 commented on docs/locale/ko/LC_MESSAGES/vfolder/vfolder.po
>  "모델 서비스를 시작해봅시다."
```suggestion
"모델 서비스를 시작하는 방법에 대해 서술합니다. "
```

2024-11-13 14:00 UTC, YEONFEEL96 reviewed
LGTM

2024-11-18 02:36 UTC, ironAiken2 commented
Can you change the status to approve? :)

2024-11-20 05:24 UTC, YEONFEEL96 approved these changes
Changed my stat to approved.

2024-11-22 05:36 UTC, ironAiken2 commented
### Merge activity

* **Nov 22, 12:36 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/lablup/backend.ai-docs-webui/89).

2024-11-22 05:43 UTC, merged